export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_MORE_CHARACTERS = 'GET_MORE_CHARACTERS';
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';
export const KILL_CHARACTER = 'KILL_CHARACTER';